portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wines.urls'))
]

wines/urls.py
from django.urls import path, include
from wines.views import my_wines, search_wine

app_name = "wines"


urlpatterns = [
    path("", my_wines, name="my-wines"),
    path("search-wine", search_wine, name="search-wine"),
    ]

wines/models.py
from django.db import models





class ColourModel(models.Model):

    colour=models.CharField(max_length=254)

    def __str__(self):
        return f"{self.colour}"


class WineModel(models.Model):
    """ model for wines"""
    name = models.CharField(max_length=254)
    strain = models.CharField(max_length=254)
    colour = models.ForeignKey(ColourModel, on_delete=models.CASCADE)
    image = models.CharField(max_length=254)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    rating = models.IntegerField(default=100)

    def __str__(self):
        return f"{self.name}"

wines/views.py
from django.shortcuts import render
from wines.models import WineModel
from django.contrib.auth.decorators import login_required




# @login_required
def my_wines(request):
    wines = WineModel.objects.all()
    wine_types = WineModel.objects.values_list("strain", flat=True).distinct()
    return render(request, "my-wines.html", {"wines": wines,"wine_types": wine_types})


@login_required
def search_wine(request):
    queryset = WineModel.objects.filter(strain__contains=request.GET['query'])

    wine_types = WineModel.objects.values_list("strain", flat=True).distinct()


    return render(request, "my-wines.html", {"queryset": queryset, "wine_types": wine_types})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Holiday Planner </title>
  <meta name="Description"
        content="Holiday Planner">

  <!-- Materialize link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->

  <!-- FontAwesome Styles-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css"
        integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
  <!-- Fonts-->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600&display=swap" rel="stylesheet">
  <!-- jQuery-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <!-- Material Icons <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->


   <!-- Bootstrap 5.0-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">



  <!-- Custom Styles-->
  <link href="{% static 'css/custom-styles.css' %}" rel="stylesheet"/>
  <link href="{% static 'css/navbar.css' %}" rel="stylesheet"/>
  <link href="{% static 'css/data.css' %}" rel="stylesheet"/>


  {% block extrahead %}

  {% endblock %}
</head>

<body>
<div id="wrapper">
  <!-- TOP NAVBAR -->
  {% block navbar %}
  <nav class="navbar navbar-default top-navbar" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'wines:my-wines' %}">
        <img src="{% static 'img/tenerife-icon.jpg' %}" alt="Tenerife" class="img-logo">
        <span style=""> Holiday Planner</span>
      </a>
    </div>
    <ul class="nav navbar-top-links navbar-right">
       {% if user.is_authenticated %}
        <li><span><a class="nav-link" href="/admin/">Admin </a></span>
        </li>

             <li><span><a class="nav-link" href="{% url 'wines:my-wines' %}">Wines </a></span>
        </li>

      <li>
          <form method="post" action="">
            {% csrf_token %}
            <span><button class="nav-button">Logout</button></span>
          </form>
        </li>

      {% else %}
         <li><span><a class="nav-link" href="">Login</a></span>
        </li>
        {% endif %}
    </ul>
  </nav>

  <div class="topnav">
    <a class="navbar-brand" href="/">
      <img src="{% static 'img/tenerife-icon.jpg' %}" alt="Tenerife" class="img-logo">
    </a>

    <a href="javascript:void(0);" class="icon" onclick="dropdown()">
      <i class="fa fa-bars"></i>
    </a>
  </div>
  {% endblock %}

  {% block content %}

  {% endblock %}

  <!-- /. WRAPPER  -->
  <div class="footer">
    <p><a target="_blank" href="https://www.freeprivacypolicy.com/privacy/view/9b972ff9a2aaeda03f07216c15625791/">Privacy
      Policy</a> • © 2019 - 2020 www.holidayplanner.com - All Rights Reserved • Powered by Septellar &trade;</p>
  </div>
</div>
<!-- Bootstrap Js -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<!-- custom JS -->
<script src="{% static 'js/custom-scripts.js' %}"></script>

</body>

</html>

wines/templates/my-wines.html
{% extends "base.html" %} {% load static %}


{% block content %}

<div id="page-index">
    <div class="dashboard-cards">
        <br><br><br>


        <div class="row plain-element">
            <div class="col col-sm-12 col-md-12 col-lg-1 plain-element"></div>
            <div class="col col-sm-12 col-md-12 col-lg-10  plain-element" id="restaurantsColumn">

                <div class="row plain-element">
                    <div class="card card-side wine-dashboard">
                        <a href="{% url 'wines:my-wines' %}">
                            <div class="section-heading">
                                Favourite <b>Wines </b>
                            </div>
                        </a>
                        <div class="row row-search">


                            {% if wine_types %}
                            {% for element in wine_types %}

                            <form action="{% url 'wines:search-wine' %}"
                                  class="col col-sm-12 col-md-4 col-lg-2   add-form" method="GET">
                                {% csrf_token %}
                                <input type="hidden" id="query" name="query" value="{{element}}">

                                <button type="submit" class="btn btn-pill"> {{element}}</button>

                            </form>

                            {% endfor %}
                            {% endif %}
                        </div>

                    </div>
                    <br>
                    <div class="row plain-element">
                        <div class="row plain-element">

                            {% for element in wines %}

                            <div class="col col-sm-4 col-md-3 col-lg-2">
                                <div class="wine-card {{ element.colour }}-wine">
                                    <div class="row plain-element">
                                        <img src="{{ element.image }}" alt="wine" class="img-restaurants">

                                    </div>
                                    <div class="row plain-element">
                                        <h5>{{element.name}}</h5>
                                        <h6>{{element.strain}} </h6>
                                        <div class="row plain-element">

                                            <div class="col col-sm-6 col-md-6 col-lg-6 left-align">
                                                <p>{{element.price}}€ </p>
                                            </div>
                                            <div class="col col-sm-6 col-md-6 col-lg-6 right-align">
                                                <p>{{element.rating}}/5</p>
                                            </div>

                                        </div>
                                    </div>
                                </div>

                            </div>
                            {% endfor %}
                            {% if queryset %}
                            {% for element in queryset %}
                            <div class="col col-sm-4 col-md-4 col-lg-2">

                                <div class="wine-card {{ element.colour }}-wine">
                                    <div class="row plain-element">
                                        <img src="{{ element.image }}" alt="wine" class="img-restaurants">

                                    </div>
                                    <div class="row plain-element">
                                        <h5>{{element.name}}</h5>
                                        <h6>{{element.strain}} </h6>
                                        <div class="row plain-element">

                                            <div class="col col-sm-6 col-md-6 col-lg-6 left-align">
                                                <p>{{element.price}}€ </p>
                                            </div>
                                            <div class="col col-sm-6 col-md-6 col-lg-6 right-align">
                                                <p>{{element.rating}}/5</p>
                                            </div>

                                        </div>
                                    </div>
                                </div>

                            </div>

                            {% endfor %}
                            {% endif %}

                        </div>
                    </div>
                    <div class="row plain-element">


                    </div>
                </div>
            </div>

            <div class="row row-break"></div>
        </div>
    </div>
    <div class="col col-sm-12 col-md-12 col-lg-1 plain-element"></div>

</div>



{% endblock %}